// ==== Diccionario de traducciones ====
const translations = {
  es: {
    // --- Header & Navbar ---
    nav_home:           'Inicio',
    nav_library:        'Biblioteca',
    nav_merch:          'Mercancía',
    nav_about:          'Nosotros',
    nav_contact:        'Contacto',
    nav_maintenance:    'Mantenimiento',
    nav_language:       '🌎',
    nav_sign_in:        'Iniciar sesión',
    nav_register:       'Registrarse',
    user_label:         'Usuario:',
    email_label:        'Correo:',
    avatar_change:      'Cambiar imagen',
    nav_sign_out:       'Cerrar sesión',
    lang_spanish:       'Español',
    lang_english:       'English',
    lang_portuguese:    'Português',
    lang_chinese:       '中文',
    lang_japanese:      '日本語',
    lang_korean:        '한국어',
    lang_cyrillic:      'Кириллица',

    // --- index.html ---
    page_title_index:   'Página Inicial',
    carousel_title_gta: 'GTA VI',
    carousel_desc_gta:  'El esperado juego de mundo abierto de Rockstar Games, ambientado en Florida ficticia.',
    carousel_button:    'Información',
    carousel_title_doom:'Doom The Dark Ages',
    carousel_desc_doom: 'FPS brutal en un mundo medieval, precuela de DOOM (2016) y DOOM Eternal.',
    carousel_title_mc:  'Minecraft',
    carousel_desc_mc:   'Sandbox donde exploras, construyes y sobrevives en mundos generados por bloques.',
    carousel_prev:      'Anterior',
    carousel_next:      'Siguiente',
    ods_label:          'ODS:',
    ods_text:           'A través del juego, los alumnos detectan y reportan problemas, promoviendo participación activa y cuidado del entorno universitario.',
    game_label:         'Juego:',
    game_text:          'Campus Bonanza es un RPG educativo donde los estudiantes resuelven problemas del campus mediante minijuegos, fomentando participación.',
    scope_label:        'Alcance:',
    scope_text:         'El juego está diseñado para estudiantes del Campus Monterrey e incluye minijuegos, tienda de mejoras, sistema de puntuaciones y reporte de incidentes. Funciona en navegadores modernos mediante WebGL.',

    // --- biblioteca.html ---
    lib_title:          'Juego',
    lib_heading:        'Biblioteca',
    lib_game1_title:    'Campus Bonanza',
    lib_game1_button:   'Jugar',

    // --- Contacto.html ---
    contact_title:      'Contacto - LEXA Studios',
    contact_heading:    'Contáctanos',
    contact_form_title: 'Formulario de Contacto',
    contact_name:       'Nombre',
    contact_email:      'Correo electrónico',
    contact_message:    'Mensaje',
    contact_send:       'Enviar',
    contact_location:   'Ubicación',
    contact_follow:     'Síguenos',

    // --- Admin.html ---
    admin_title:        'Panel de Control',
    admin_col_user:     'Usuario',
    admin_col_email:    'Correo',
    admin_col_comment:  'Comentario',
    admin_col_date:     'Fecha',
    admin_col_status:   'Estatus',

    // --- Nosotros.html ---
    nosotros_title:     'LEXA Studios',
    about_description:  'LEXA Studios es un equipo de estudiantes del Tecnológico de Monterrey enfocado en desarrollar soluciones interactivas con impacto social. Nuestro proyecto principal, Campus Bonanza, es un videojuego estilo RPG diseñado para mejorar el ambiente universitario involucrando a los alumnos en la detección y resolución de problemas del campus. Combinamos tecnología, creatividad y propósito social para crear experiencias innovadoras que promueven el bienestar, la colaboración y la conciencia comunitaria.',
    about_mission:      'Misión',
    about_mission_text: 'Desarrollar herramientas interactivas y educativas que promuevan la participación estudiantil en la mejora del entorno universitario, fomentando el aprendizaje, la responsabilidad social y el trabajo colaborativo.',
    about_values:       'Valores',
    about_values_text:  'Compromiso, creatividad, innovación, colaboración, responsabilidad social y respeto por la comunidad estudiantil y su entorno.',
    about_vision:       'Visión',
    about_vision_text:  'Ser referentes en el desarrollo de soluciones gamificadas que inspiren un cambio positivo en las comunidades educativas mediante tecnología y diseño centrado en el usuario.',
    tech_title:         'Tecnologías Utilizadas',
    scope_heading:      'Alcance',
    scope_text:         'Campus Bonanza está enfocado en estudiantes del Campus Monterrey. El sistema incluye registro de usuario, login por roles, minijuegos, tienda de mejoras, leaderboard y sistema de reporte de incidentes. Funciona en navegadores modernos a través de WebGL y tiene potencial de expansión con nuevas mecánicas, escenarios y mejoras basadas en IA.',
    team_alexis_name:   'Alexis',
    team_alexis_bio:    'Estudiante ITC en el Tecnológico de Monterrey. Especialista en backend con experiencia en APIs, análisis de datos y bases de datos relacionales. Apasionado por sistemas embebidos e innovación educativa. Participó en proyectos como WasteWise y Pythoku, y es Microsoft Learn Student Ambassador Mentee.',
    team_axel_name:     'Axel',
    team_axel_bio:      'Estudiante ITC en el Tecnológico de Monterrey, enfocado en desarrollo frontend y plataformas web. Contribuyó a la plataforma Cuwi y participó en Hackathon y Datathon. Hábil en Python, C++, MATLAB, HTML, CSS y JavaScript. Creativo en UX/UI, modelado en Blender y gestión de proyectos.',
    team_marco_name:    'Marco',
    team_marco_bio:     'Estudiante ITC con habilidades creativas y técnicas. Desarrollador frontend, artista digital y animador con experiencia en Glup App y ganador del reto Oracle APEX en HackMTY. Experto en Blender y SQL.',
    team_david_name:    'David',
    team_david_bio:     'Estudiante ITC en el Tecnológico de Monterrey. Profesor de inglés con habilidades técnicas en Python, C++, MATLAB, Arduino y R. Combina perfil técnico y educativo con atención al detalle. Apasionado de los idiomas, la programación y diseño de interfaces.',
    team_fernando_name: 'Fernando',
    team_fernando_bio:  'Estudiante ITC con habilidades en automatización, trabajo en equipo y pensamiento crítico. Desarrolló un proyecto de hogar inteligente con control Wi-Fi y coordinó logística en hackathon nacional. Colaboró con ONGs en gestión de ayuda técnica y estudios de mercado.',
    team_download_cv:   'Descargar CV',

    // --- registro.html ---
    register_title:     'Registro',
    register_user:      'Usuario',
    register_email:     'Correo',
    register_password:  'Contraseña',
    register_role:      'Selecciona un rol:',
    register_role_user: 'Usuario',
    register_role_admin:'Administrador',
    register_submit:    'Registrar',
    register_have_account:'¿Ya tienes cuenta?',

    // --- inicioSesion.html ---
    login_title:        'Iniciar sesión',
    login_username:     'Usuario',
    login_password:     'Contraseña',
    login_button:       'Iniciar sesión',
    login_no_account:   '¿No tienes cuenta?',
    login_sign_in:      "Inicia sesión",


    // --- Tienda.html ---
    shop_title:          'Tienda - LEXA Studios',
    shop_heading:        'Productos',
    shop_item1_name:     'LEXA Shirt (Black)',
    shop_item1_price:    '$350',
    shop_item2_name:     'LEXA Shirt (White)',
    shop_item2_price:    '$350',
    shop_item3_name:     'Pixel Runner Shirt',
    shop_item3_price:    '$350',
    shop_item4_name:     'Prof. Michi Mug',
    shop_item4_price:    '$150',
    shop_item5_name:     'LEXA Cap (Black)',
    shop_item5_price:    '$150',
    shop_item6_name:     'LEXA Cap (White)',
    shop_item6_price:    '$150',
    shop_item7_name:     'Runner Cap',
    shop_item7_price:    '$150',
    shop_item8_name:     'Pixel Runner Keychain',
    shop_item8_price:    '$150',
    shop_buy:            'Comprar',
    shop_modal_title:    'Nombre del Producto',
    shop_modal_desc:     'Descripción del Producto',
    shop_size_label:     'Talla:',
    shop_add_cart:       'Agregar al carrito',
    shop_cart:           'Carrito',
    shop_pay:            'Pagar',


    admin_new_admin:     'Crear Nuevo Administrador',
    admin_create_btn:    'Crear Admin',
    'contact-messages':  'Mensajes de Contacto',
    pw_min_length: "Mínimo 8 caracteres",
    pw_uppercase:  "Al menos una mayúscula",
    pw_lowercase:  "Al menos una minúscula",
    pw_digit:      "Al menos un número",
    pw_special:    "Al menos un carácter especial",

    // --- juego.html ---
    game_title:         'Juego',
    game_page_title:    'Campus Bonanza',
    game_unavailable:   'Juego SOLO disponible en PC',
    scoreboard_title:   'Tabla de Puntuaciones',
    scoreboard_col_name: 'Nombre',
    scoreboard_col_score:'Puntuación',
    faq_heading:        'Preguntas Frecuentes',
    faq_q1:             '¿Cómo se juega?',
    faq_a1:             'Campus Bonanza es un juego RPG donde participas en minijuegos que representan incidentes reales en el campus.',
    faq_q2:             '¿Cómo se gana?',
    faq_a2:             'Ganas acumulando puntos al resolver incidentes rápidamente y de manera eficiente.',
    faq_q3:             '¿Cómo funciona el sistema de puntuaciones?',
    faq_a3:             'Recibes puntos por cada tarea resuelta y se muestran en el leaderboard.',
    faq_q4:             '¿Cómo me registro en la tabla de puntuaciones?',
    faq_a4:             'Crea una cuenta con tu nombre, correo y contraseña; tus resultados se guardarán automáticamente.',
    faq_q5:             '¿Cómo funcionan los power-ups?',
    faq_a5:             'Usa los puntos obtenidos para comprar power-ups que te den ventajas como tiempo extra o mayor velocidad.'
  },

  en: {
    // --- Header & Navbar ---
    nav_home:           'Home',
    nav_library:        'Library',
    nav_merch:          'Merch',
    nav_about:          'About us',
    nav_contact:        'Contact',
    nav_maintenance:    'Maintenance',
    nav_language:       '🌎',
    nav_sign_in:        'Sign in',
    nav_register:       'Register',
    user_label:         'User:',
    email_label:        'Email:',
    avatar_change:      'Change avatar',
    nav_sign_out:       'Sign out',
    lang_spanish:       'Español',
    lang_english:       'English',
    lang_portuguese:    'Português',
    lang_chinese:       '中文',
    lang_japanese:      '日本語',
    lang_korean:        '한국어',
    lang_cyrillic:      'Кириллица',

    // --- index.html ---
    page_title_index:   'Home Page',
    carousel_title_gta: 'GTA VI',
    carousel_desc_gta:  'The highly anticipated open-world game by Rockstar Games set in a fictional Florida.',
    carousel_button:    'Information',
    carousel_title_doom:'Doom The Dark Ages',
    carousel_desc_doom: 'A brutal FPS set in a medieval world, serving as a prequel to DOOM (2016) and DOOM Eternal.',
    carousel_title_mc:  'Minecraft',
    carousel_desc_mc:   'The best sandbox where you explore, build, and survive in procedurally generated worlds.',
    carousel_prev:      'Previous',
    carousel_next:      'Next',
    ods_label:          'SDG:',
    ods_text:           'Through the game, students detect and report issues, promoting active participation and care for the university environment.',
    game_label:         'Game:',
    game_text:          'Campus Bonanza is an educational RPG where Tec students solve campus issues through minigames, boosting engagement.',
    scope_label:        'Scope:',
    scope_text:         'The game is designed for Monterrey Campus students. It includes minigames, a power-up store, a scoring system, and incident reporting. Runs on modern browsers via WebGL.',

    // --- biblioteca.html ---
    lib_title:          'Game',
    lib_heading:        'Library',
    lib_game1_title:    'Campus Bonanza',
    lib_game1_button:   'Play',

    // --- Contacto.html ---
    contact_title:      'Contact - LEXA Studios',
    contact_heading:    'Contact Us',
    contact_form_title: 'Contact Form',
    contact_name:       'Name',
    contact_email:      'Email',
    contact_message:    'Message',
    contact_send:       'Send',
    contact_location:   'Location',
    contact_follow:     'Follow Us',

    // --- Admin.html ---
    admin_title:        'Control Panel',
    admin_col_user:     'User',
    admin_col_email:    'Email',
    admin_col_comment:  'Comment',
    admin_col_date:     'Date',
    admin_col_status:   'Status',

    // --- Nosotros.html ---
    nosotros_title:     'LEXA Studios',
    about_description:  'LEXA Studios is a team of students from Tecnológico de Monterrey focused on developing interactive solutions with social impact. Our main project, Campus Bonanza, is an RPG-style video game designed to improve the university environment by engaging students in the detection and resolution of campus issues. We combine technology, creativity, and social purpose to create innovative experiences that promote well-being, collaboration, and community awareness.',
    about_mission:      'Mission',
    about_mission_text: 'To develop interactive and educational tools that promote student participation in improving the university environment, encouraging learning, social responsibility, and collaborative work.',
    about_values:       'Values',
    about_values_text:  'Commitment, creativity, innovation, collaboration, social responsibility, and respect for the student community and its environment.',
    about_vision:       'Vision',
    about_vision_text:  'To become a benchmark in the development of gamified solutions that inspire positive change in educational communities through technology and user-centered design.',
    tech_title:         'Technologies Used',
    scope_heading:      'Scope',
    scope_text:         'Campus Bonanza is focused on students at the Monterrey Campus. The system includes user registration, role-based login, minigames, power-up store, leaderboard, and incident reporting. Runs on modern browsers via WebGL and has growth potential with new mechanics, scenarios, and AI enhancements.',
    team_alexis_name:   'Alexis',
    team_alexis_bio:    'ITC student at Tecnológico de Monterrey. Backend specialist with experience in APIs, data analysis, and relational databases. Passionate about embedded systems and educational innovation. Participated in projects such as WasteWise and Pythoku, and is a Microsoft Learn Student Ambassador Mentee.',
    team_axel_name:     'Axel',
    team_axel_bio:      'ITC student at Tecnológico de Monterrey, focused on front-end development and web platforms. Contributed to the Cuwi platform and participated in Hackathons and Datathons. Skilled in Python, C++, MATLAB, HTML, CSS, and JavaScript. Creative problem-solver with UX/UI design experience, Blender modeling, and strong project management skills.',
    team_marco_name:    'Marco',
    team_marco_bio:     'ITC student with both creative and technical skills. Front-end developer, digital artist, and animator with experience on Glup App and winner of the Oracle APEX challenge at HackMTY. Proficient in Blender and SQL.',
    team_david_name:    'David',
    team_david_bio:     'ITC student at Tecnológico de Monterrey. Experienced English teacher with technical skills in Python, C++, MATLAB, Arduino, and R. Combines technical and educational profile with attention to detail. Passionate about languages, programming, and interface design.',
    team_fernando_name: 'Fernando',
    team_fernando_bio:  'ITC student skilled in automation, teamwork, and critical thinking. Developed a smart home project with Wi-Fi control and coordinated logistics at a national hackathon. Also collaborated with NGOs by managing technical aid deliveries and conducting market studies.',
    team_download_cv:   'Download CV',

    // --- registro.html ---
    register_title:     'Register',
    register_user:      'User',
    register_email:     'Email',
    register_password:  'Password',
    register_role:      'Select a Role:',
    register_role_user: 'User',
    register_role_admin:'Administrator',
    register_submit:    'Register',
    register_have_account:'Already have an account?',

    // --- inicioSesion.html ---
    login_title:        'Sign In',
    login_username:     'Username',
    login_password:     'Password',
    login_button:       'Sign In',
    login_no_account:   "Don't have an account?",
    login_sign_in:      "Sign In",

    // --- Tienda.html ---
    shop_title:          'Shop - LEXA Studios',
    shop_heading:        'Products',
    shop_item1_name:     'LEXA Shirt (Black)',
    shop_item1_price:    '$350',
    shop_item2_name:     'LEXA Shirt (White)',
    shop_item2_price:    '$350',
    shop_item3_name:     'Pixel Runner Shirt',
    shop_item3_price:    '$350',
    shop_item4_name:     'Prof. Michi Mug',
    shop_item4_price:    '$150',
    shop_item5_name:     'LEXA Cap (Black)',
    shop_item5_price:    '$150',
    shop_item6_name:     'LEXA Cap (White)',
    shop_item6_price:    '$150',
    shop_item7_name:     'Runner Cap',
    shop_item7_price:    '$150',
    shop_item8_name:     'Pixel Runner Keychain',
    shop_item8_price:    '$150',
    shop_buy:            'Buy',
    shop_modal_title:    'Product Name',
    shop_modal_desc:     'Product Description',
    shop_size_label:     'Size:',
    shop_add_cart:       'Add to Cart',
    shop_cart:           'Cart',
    shop_pay:            'Pay',


    admin_new_admin:     'Create New Administrator',
    admin_create_btn:    'Create Admin',
    'contact-messages':  'Contact Messages',
    pw_min_length: "At least 8 characters",
    pw_uppercase:  "At least one uppercase letter",
    pw_lowercase:  "At least one lowercase letter",
    pw_digit:      "At least one number",
    pw_special:    "At least one special character",

    // --- juego.html ---
    game_title:         'Game',
    game_page_title:    'Campus Bonanza',
    game_unavailable:   'Game ONLY available on PC',
    scoreboard_title:   'ScoreBoard',
    scoreboard_col_name: 'Name',
    scoreboard_col_score:'Score',
    faq_heading:        'FAQs',
    faq_q1:             'How do you play?',
    faq_a1:             'Campus Bonanza is an RPG-style game where you participate in minigames that represent real campus incidents.',
    faq_q2:             'How do you win?',
    faq_a2:             'You win by accumulating points for solving incidents quickly and efficiently.',
    faq_q3:             'How does the score system work?',
    faq_a3:             'Each time you solve a task, you earn points that appear on the leaderboard.',
    faq_q4:             'How do I register on the scoreboard?',
    faq_a4:             'Create an account with your name, email, and password; your results will be saved automatically.',
    faq_q5:             'How do power-ups work?',
    faq_a5:             'Use the points you’ve earned to purchase power-ups that give you advantages like extra time or increased speed.'
  },

  pt: {
    // --- Header & Navbar ---
    nav_home:           'Início',
    nav_library:        'Biblioteca',
    nav_merch:          'Mercadoria',
    nav_about:          'Sobre nós',
    nav_contact:        'Contato',
    nav_maintenance:    'Manutenção',
    nav_language:       '🌎',
    nav_sign_in:        'Entrar',
    nav_register:       'Registrar',
    user_label:         'Usuário:',
    email_label:        'Email:',
    avatar_change:      'Mudar avatar',
    nav_sign_out:       'Sair',
    lang_spanish:       'Español',
    lang_english:       'English',
    lang_portuguese:    'Português',
    lang_chinese:       '中文',
    lang_japanese:      '日本語',
    lang_korean:        '한국어',
    lang_cyrillic:      'Кириллица',


    // --- index.html ---
    page_title_index:   'Página Inicial',
    carousel_title_gta: 'GTA VI',
    carousel_desc_gta:  'O tão aguardado jogo de mundo aberto da Rockstar Games, ambientado em uma Flórida fictícia.',
    carousel_button:    'Informações',
    carousel_title_doom:'Doom The Dark Ages',
    carousel_desc_doom: 'FPS brutal em um mundo medieval, prelúdio de DOOM (2016) e DOOM Eternal.',
    carousel_title_mc:  'Minecraft',
    carousel_desc_mc:   'O melhor sandbox onde você explora, constrói e sobrevive em mundos gerados por blocos.',
    carousel_prev:      'Anterior',
    carousel_next:      'Próximo',
    ods_label:          'ODS:',
    ods_text:           'Através do jogo, os alunos detectam e relatam problemas, promovendo participação ativa e cuidado com o ambiente universitário.',
    game_label:         'Jogo:',
    game_text:          'Campus Bonanza é um RPG educacional onde alunos resolvem problemas do campus por meio de minijogos, promovendo engajamento.',
    scope_label:        'Escopo:',
    scope_text:         'O jogo é projetado para estudantes do Campus Monterrey. Inclui minijogos, loja de melhorias, sistema de pontuação e relatório de incidentes. Funciona em navegadores modernos com WebGL.',

    // --- biblioteca.html ---
    lib_title:          'Jogo',
    lib_heading:        'Biblioteca',
    lib_game1_title:    'Campus Bonanza',
    lib_game1_button:   'Jogar',

    // --- Contacto.html ---
    contact_title:      'Contato - LEXA Studios',
    contact_heading:    'Contato',
    contact_form_title: 'Formulário de Contato',
    contact_name:       'Nome',
    contact_email:      'Email',
    contact_message:    'Mensagem',
    contact_send:       'Enviar',
    contact_location:   'Localização',
    contact_follow:     'Siga-nos',

    // --- Admin.html ---
    admin_title:        'Painel de Controle',
    admin_col_user:     'Usuário',
    admin_col_email:    'Email',
    admin_col_comment:  'Comentário',
    admin_col_date:     'Data',
    admin_col_status:   'Status',

    // --- Nosotros.html ---
    nosotros_title:     'LEXA Studios',
    about_description:  'LEXA Studios é uma equipe de estudantes do Tecnológico de Monterrey focada em desenvolver soluções interativas com impacto social. Nosso projeto principal, Campus Bonanza, é um videogame estilo RPG projetado para melhorar o ambiente universitário, envolvendo alunos na detecção e resolução de problemas do campus. Combinamos tecnologia, criatividade e propósito social para criar experiências inovadoras que promovem bem-estar, colaboração e consciência comunitária.',
    about_mission:      'Missão',
    about_mission_text: 'Desenvolver ferramentas interativas e educacionais que promovam a participação estudantil na melhoria do ambiente universitário, incentivando aprendizado, responsabilidade social e trabalho colaborativo.',
    about_values:       'Valores',
    about_values_text:  'Compromisso, criatividade, inovação, colaboração, responsabilidade social e respeito pela comunidade estudantil e seu entorno.',
    about_vision:       'Visão',
    about_vision_text:  'Ser referência no desenvolvimento de soluções gamificadas que inspirem mudanças positivas em comunidades educacionais por meio da tecnologia e do design centrado no usuário.',
    tech_title:         'Tecnologias Utilizadas',
    scope_heading:      'Escopo',
    scope_text:         'Campus Bonanza é voltado para estudantes do Campus Monterrey. O sistema inclui registro de usuário, login por função, minijogos, loja de melhorias, leaderboard e sistema de relato de incidentes. Funciona em navegadores modernos via WebGL e possui potencial de expansão com novas mecânicas, cenários e melhorias baseadas em IA.',
    team_alexis_name:   'Alexis',
    team_alexis_bio:    'Estudante ITC no Tecnológico de Monterrey. Especialista em backend com experiência em APIs, análise de dados e bancos de dados relacionais. Apaixonado por sistemas embarcados e inovação educacional. Participou de projetos como WasteWise e Pythoku, e é Microsoft Learn Student Ambassador Mentee.',
    team_axel_name:     'Axel',
    team_axel_bio:      'Estudante ITC no Tecnológico de Monterrey, focado em desenvolvimento frontend e plataformas web. Contribuiu para a plataforma Cuwi e participou de Hackathons e Datathons. Hábil em Python, C++, MATLAB, HTML, CSS e JavaScript. Criativo em UX/UI, modelagem em Blender e gestão de projetos.',
    team_marco_name:    'Marco',
    team_marco_bio:     'Estudante ITC com habilidades criativas e técnicas. Desenvolvedor frontend, artista digital e animador com experiência no Glup App e vencedor do desafio Oracle APEX no HackMTY. Proficiência em Blender e SQL.',
    team_david_name:    'David',
    team_david_bio:     'Estudante ITC no Tecnológico de Monterrey. Professor de inglês com habilidades técnicas em Python, C++, MATLAB, Arduino e R. Combina perfil técnico e educacional com atenção aos detalhes. Apaixonado por idiomas, programação e design de interfaces.',
    team_fernando_name: 'Fernando',
    team_fernando_bio:  'Estudante ITC com habilidades em automação, trabalho em equipe e pensamento crítico. Desenvolveu um projeto de automação residencial com controle Wi-Fi e coordenou logística em hackathon nacional. Também colaborou com ONGs na gestão de ajuda técnica e estudos de mercado.',
    team_download_cv:   'Baixar CV',

    // --- registro.html ---
    register_title:     'Registrar',
    register_user:      'Usuário',
    register_email:     'Email',
    register_password:  'Senha',
    register_role:      'Selecione uma função:',
    register_role_user: 'Usuário',
    register_role_admin:'Administrador',
    register_submit:    'Registrar',
    register_have_account:'Já tem uma conta?',

    // --- inicioSesion.html ---
    login_title:        'Entrar',
    login_username:     'Usuário',
    login_password:     'Senha',
    login_button:       'Entrar',
    login_no_account:   'Não tem uma conta?',
    login_sign_in:      "Iniciar sessão",


    // --- Tienda.html ---
    shop_title:          'Loja - LEXA Studios',
    shop_heading:        'Produtos',
    shop_item1_name:     'LEXA Shirt (Black)',
    shop_item1_price:    '$350',
    shop_item2_name:     'LEXA Shirt (White)',
    shop_item2_price:    '$350',
    shop_item3_name:     'Pixel Runner Shirt',
    shop_item3_price:    '$350',
    shop_item4_name:     'Prof. Michi Mug',
    shop_item4_price:    '$150',
    shop_item5_name:     'LEXA Cap (Black)',
    shop_item5_price:    '$150',
    shop_item6_name:     'LEXA Cap (White)',
    shop_item6_price:    '$150',
    shop_item7_name:     'Runner Cap',
    shop_item7_price:    '$150',
    shop_item8_name:     'Pixel Runner Keychain',
    shop_item8_price:    '$150',
    shop_buy:            'Comprar',
    shop_modal_title:    'Nome do Produto',
    shop_modal_desc:     'Descrição do Produto',
    shop_size_label:     'Tamanho:',
    shop_add_cart:       'Adicionar ao Carrinho',
    shop_cart:           'Carrinho',
    shop_pay:            'Pagar',

    admin_new_admin:     'Criar Novo Administrador',
    admin_create_btn:    'Criar Admin',
    'contact-messages':  'Mensagens de Contato',
    pw_min_length: "Mínimo de 8 caracteres",
    pw_uppercase:  "Pelo menos uma letra maiúscula",
    pw_lowercase:  "Pelo menos uma letra minúscula",
    pw_digit:      "Pelo menos um número",
    pw_special:    "Pelo menos um caractere especial",

    // --- juego.html ---
    game_title:         'Jogo' ,
    game_page_title:    'Campus Bonanza',
    game_unavailable:   'Jogo não disponível',
    scoreboard_title:   'Placar',
    scoreboard_col_name: 'Nome',
    scoreboard_col_score:'Pontuação',
    faq_heading:        'Perguntas Frequentes',
    faq_q1:             'Como jogar?',
    faq_a1:             'Campus Bonanza é um jogo estilo RPG onde você participa de minijogos que representam incidentes reais no campus.',
    faq_q2:             'Como ganhar?',
    faq_a2:             'Você ganha acumulando pontos ao resolver incidentes rápida e eficientemente.',
    faq_q3:             'Como funciona o sistema de pontuação?',
    faq_a3:             'Cada vez que você resolve uma tarefa, recebe pontos que aparecem no placar.',
    faq_q4:             'Como me registro no placar?',
    faq_a4:             'Crie uma conta com seu nome, email e senha; seus resultados serão salvos automaticamente.',
    faq_q5:             'Como os power-ups funcionam?',
    faq_a5:             'Use pontos ganhos para comprar power-ups que lhe dão vantagens como tempo extra ou aumento de velocidade.'
  },

  zh: {
    // --- Header & Navbar ---
    nav_home:           '首页',
    nav_library:        '图书馆',
    nav_merch:          '商品',
    nav_about:          '关于我们',
    nav_contact:        '联系',
    nav_maintenance:    '维护',
    nav_language:       '🌎',
    nav_sign_in:        '登录',
    nav_register:       '注册',
    user_label:         '用户：',
    email_label:        '邮箱：',
    avatar_change:      '更换头像',
    nav_sign_out:       '登出',
    lang_spanish:       'Español',
    lang_english:       'English',
    lang_portuguese:    'Português',
    lang_chinese:       '中文',
    lang_japanese:      '日本語',
    lang_korean:        '한국어',
    lang_cyrillic:      'Кириллица',

    // --- index.html ---
    page_title_index:   '首页',
    carousel_title_gta: 'GTA VI',
    carousel_desc_gta:  'Rockstar Games 期待已久的开放世界游戏，背景设定在虚构的佛罗里达。',
    carousel_button:    '信息',
    carousel_title_doom:'Doom The Dark Ages',
    carousel_desc_doom: '设定在中世纪世界的残酷射击游戏，是 DOOM（2016）和 DOOM Eternal 的前传。',
    carousel_title_mc:  'Minecraft',
    carousel_desc_mc:   '最佳沙盒游戏，可在程序生成的方块世界中探索、建造和生存。',
    carousel_prev:      '上一张',
    carousel_next:      '下一张',
    ods_label:          '可持续发展目标：',
    ods_text:           '通过游戏，学生发现并报告问题，促进积极参与和对大学环境的关注。',
    game_label:         '游戏：',
    game_text:          'Campus Bonanza 是一个教育 RPG，学生通过小游戏解决校园问题，提升参与度。',
    scope_label:        '范围：',
    scope_text:         '该游戏面向蒙特雷校区学生，包含小游戏、道具商店、计分系统和事故报告。可通过 WebGL 在现代浏览器中访问。',

    // --- biblioteca.html ---
    lib_title:          '游戏',
    lib_heading:        '图书馆',
    lib_game1_title:    'Campus Bonanza',
    lib_game1_button:   '游玩',

    // --- Contacto.html ---
    contact_title:      '联系 - LEXA Studios',
    contact_heading:    '联系我们',
    contact_form_title: '联系表格',
    contact_name:       '姓名',
    contact_email:      '邮箱',
    contact_message:    '留言',
    contact_send:       '发送',
    contact_location:   '位置',
    contact_follow:     '关注我们',

    // --- Admin.html ---
    admin_title:        '控制面板',
    admin_col_user:     '用户',
    admin_col_email:    '邮箱',
    admin_col_comment:  '评论',
    admin_col_date:     '日期',
    admin_col_status:   '状态',

    // --- Nosotros.html ---
    nosotros_title:     'LEXA Studios',
    about_description:  'LEXA Studios 是蒙特雷理工学院学生组成的团队，致力于开发具有社会影响的互动解决方案。我们的主要项目 Campus Bonanza 是一款 RPG 风格的视频游戏，旨在通过让学生参与校园问题的发现和解决来改善大学环境。我们结合技术、创意和社会目标，创建创新体验，促进福祉、协作和社区意识。',
    about_mission:      '使命',
    about_mission_text: '开发互动且教育性的工具，促进学生参与改善大学环境，鼓励学习、社会责任和协作工作。',
    about_values:       '价值观',
    about_values_text:  '承诺、创造力、创新、协作、社会责任以及对学生群体及其环境的尊重。',
    about_vision:       '愿景',
    about_vision_text:  '成为通过技术和以用户为中心设计，激发教育社区积极变化的游戏化解决方案标杆。',
    tech_title:         '使用技术',
    scope_heading:      '范围',
    scope_text:         'Campus Bonanza 关注蒙特雷校区的学生。系统包含用户注册、基于角色的登录、小游戏、道具商店、排行榜和事故报告系统。可在现代浏览器通过 WebGL 运行，并具有通过新机制、场景和基于 AI 的增强扩展的潜力。',
    team_alexis_name:   'Alexis',
    team_alexis_bio:    '蒙特雷理工学院 ITC 学生。后端专家，拥有 API、数据分析和关系型数据库经验。热衷于嵌入式系统和教育创新。参与项目包括 WasteWise 和 Pythoku，是 Microsoft Learn 学生大使学员。',
    team_axel_name:     'Axel',
    team_axel_bio:      '蒙特雷理工学院 ITC 学生，专注于前端开发和 Web 平台。贡献于 Cuwi 平台，参加 Hackathon 和 Datathon。擅长 Python、C++、MATLAB、HTML、CSS 和 JavaScript。创意 UX/UI 设计师，Blender 建模高手，项目管理能力强。',
    team_marco_name:    'Marco',
    team_marco_bio:     '具有创造性和技术能力的 ITC 学生。前端开发者、数字艺术家和动画师，参与项目包括 Glup App，并在 HackMTY Oracle APEX 挑战赛中获胜。精通 Blender 和 SQL。',
    team_david_name:    'David',
    team_david_bio:     '蒙特雷理工学院 ITC 学生。经验丰富的英语教师，具备 Python、C++、MATLAB、Arduino 和 R 的技术技能。结合技术和教育背景，注重细节。热爱语言、编程和界面设计。',
    team_fernando_name: 'Fernando',
    team_fernando_bio:  'ITC 学生，擅长自动化、团队协作和批判性思维。开发了带 Wi-Fi 控制的智能家居项目，协调全国性 hackathon 的物流。曾与非政府组织合作，管理技术援助交付并进行市场研究。',
    team_download_cv:   '下载简历',

    // --- registro.html ---
    register_title:     '注册',
    register_user:      '用户',
    register_email:     '邮箱',
    register_password:  '密码',
    register_role:      '选择角色：',
    register_role_user: '用户',
    register_role_admin:'管理员',
    register_submit:    '注册',
    register_have_account:'已有账户？',

    // --- inicioSesion.html ---
    login_title:        '登录',
    login_username:     '用户名',
    login_password:     '密码',
    login_button:       '登录',
    login_no_account:   '没有账户？',
    login_sign_in:      "登录",
    

    // --- Tienda.html ---
    shop_title:          '商店 - LEXA Studios',
    shop_heading:        '产品',
    shop_item1_name:     'LEXA 衬衫（黑色）',
    shop_item1_price:    '$350',
    shop_item2_name:     'LEXA 衬衫（白色）',
    shop_item2_price:    '$350',
    shop_item3_name:     'Pixel Runner 衬衫',
    shop_item3_price:    '$350',
    shop_item4_name:     'Prof. Michi 杯子',
    shop_item4_price:    '$150',
    shop_item5_name:     'LEXA 帽子（黑色）',
    shop_item5_price:    '$150',
    shop_item6_name:     'LEXA 帽子（白色）',
    shop_item6_price:    '$150',
    shop_item7_name:     '竞跑者帽子',
    shop_item7_price:    '$150',
    shop_item8_name:     'Pixel Runner 钥匙扣',
    shop_item8_price:    '$150',
    shop_buy:            '购买',
    shop_modal_title:    '产品名称',
    shop_modal_desc:     '产品描述',
    shop_size_label:     '尺码：',
    shop_add_cart:       '加入购物车',
    shop_cart:           '购物车',
    shop_pay:            '支付',

    admin_new_admin:     '创建新管理员',
    admin_create_btn:    '创建管理员',
    'contact-messages':  '联系消息',
    pw_min_length: "至少8个字符",
    pw_uppercase:  "至少一个大写字母",
    pw_lowercase:  "至少一个小写字母",
    pw_digit:      "至少一个数字",
    pw_special:    "至少一个特殊字符",

    // --- juego.html ---
    game_title:         '游戏',
    game_page_title:    'Campus Bonanza',
    game_unavailable:   '游戏不可用',
    scoreboard_title:   '排行榜',
    scoreboard_col_name: '姓名',
    scoreboard_col_score:'分数',
    faq_heading:        '常见问题',
    faq_q1:             '怎么玩？',
    faq_a1:             'Campus Bonanza 是一款 RPG 风格的游戏，玩家参与代表校园实际事件的迷你游戏。',
    faq_q2:             '如何获胜？',
    faq_a2:             '通过快速高效地解决事件来累积积分即可获胜。',
    faq_q3:             '积分系统如何运作？',
    faq_a3:             '每次解决任务时都会获得积分，并显示在排行榜中。',
    faq_q4:             '如何在排行榜注册？',
    faq_a4:             '创建包含姓名、邮箱和密码的账户后，您的成绩会自动保存。',
    faq_q5:             '加成道具如何工作？',
    faq_a5:             '使用获得的积分购买加成道具，可使您获得额外时间或更高速度等优势。'
  },

  ja: {
    // --- Header & Navbar ---
    nav_home:           'ホーム',
    nav_library:        'ライブラリ',
    nav_merch:          '商品',
    nav_about:          '私たちについて',
    nav_contact:        'お問い合わせ',
    nav_maintenance:    'メンテナンス',
    nav_language:       '🌎',
    nav_sign_in:        'サインイン',
    nav_register:       '登録',
    user_label:         'ユーザー：',
    email_label:        'メール：',
    avatar_change:      'アバター変更',
    nav_sign_out:       'サインアウト',
    lang_spanish:       'Español',
    lang_english:       'English',
    lang_portuguese:    'Português',
    lang_chinese:       '中文',
    lang_japanese:      '日本語',
    lang_korean:        '한국어',
    lang_cyrillic:      'Кириллица',

    // --- index.html ---
    page_title_index:   'ホームページ',
    carousel_title_gta: 'GTA VI',
    carousel_desc_gta:  'Rockstar Games が贈る期待のオープンワールドゲーム、架空のフロリダが舞台。',
    carousel_button:    '情報',
    carousel_title_doom:'Doom The Dark Ages',
    carousel_desc_doom: '中世を舞台にした残酷な FPS、DOOM (2016) と DOOM Eternal の前日譚。',
    carousel_title_mc:  'Minecraft',
    carousel_desc_mc:   'ブロックで構成された世界を探索、建築、生き延びる最高のサンドボックスゲーム。',
    carousel_prev:      '前へ',
    carousel_next:      '次へ',
    ods_label:          'SDGs：',
    ods_text:           'ゲームを通じて学生が問題を発見し報告することで、積極的な参加と大学環境への配慮を促進します。',
    game_label:         'ゲーム：',
    game_text:          'Campus Bonanza は教育用 RPG で、学生がミニゲームを通じてキャンパスの問題を解決し、参加を促進します。',
    scope_label:        '範囲：',
    scope_text:         'このゲームはモンテレイキャンパスの学生向けに設計されており、ミニゲーム、パワーアップストア、スコアシステム、インシデント報告システムが含まれます。WebGL によってモダンなブラウザで利用できます。',

    // --- biblioteca.html ---
    lib_title:          'ゲーム',
    lib_heading:        'ライブラリ',
    lib_game1_title:    'Campus Bonanza',
    lib_game1_button:   'プレイ',

    // --- Contacto.html ---
    contact_title:      'お問い合わせ - LEXA Studios',
    contact_heading:    'お問い合わせ',
    contact_form_title: 'お問い合わせフォーム',
    contact_name:       '名前',
    contact_email:      'メール',
    contact_message:    'メッセージ',
    contact_send:       '送信',
    contact_location:   '場所',
    contact_follow:     'フォローする',

    // --- Admin.html ---
    admin_title:        'コントロールパネル',
    admin_col_user:     'ユーザー',
    admin_col_email:    'メール',
    admin_col_comment:  'コメント',
    admin_col_date:     '日付',
    admin_col_status:   'ステータス',

    // --- Nosotros.html ---
    nosotros_title:     'LEXA Studios',
    about_description:  'LEXA Studios はテクニカル大学モンテレイ校の学生チームで、社会的インパクトのあるインタラクティブソリューションの開発に取り組んでいます。メインプロジェクトの Campus Bonanza は、キャンパスの問題発見と解決に学生を巻き込む RPG スタイルのビデオゲームで、大学の環境を向上させることを目的としています。テクノロジー、創造力、社会的目的を組み合わせて、福祉、コラボレーション、コミュニティ意識を促進する革新的な体験を提供しています。',
    about_mission:      'ミッション',
    about_mission_text: '大学環境の改善に学生の参加を促すインタラクティブで教育的なツールを開発し、学習、社会的責任、協働を促進します。',
    about_values:       '価値観',
    about_values_text:  '献身、創造性、革新、協力、社会的責任、学生コミュニティとその環境への敬意。',
    about_vision:       'ビジョン',
    about_vision_text:  'テクノロジーとユーザー中心のデザインを通じて、教育コミュニティに前向きな変化をもたらすゲーミフィケーションソリューションのベンチマークとなること。',
    tech_title:         '使用技術',
    scope_heading:      '範囲',
    scope_text:         'Campus Bonanza はモンテレイキャンパスの学生を対象としています。システムにはユーザー登録、役割ベースのログイン、ミニゲーム、パワーアップストア、リーダーボード、インシデント報告システムが含まれます。WebGL を介してモダンブラウザで動作し、新しいメカニクス、シナリオ、AI ベースの改善によって拡張する可能性があります。',
    team_alexis_name:   'アレクシス',
    team_alexis_bio:    'テクニカル大学モンテレイ校の ITC 学生。API、データ分析、リレーショナルデータベースに精通したバックエンドスペシャリスト。組み込みシステムと教育イノベーションに情熱を持ち、WasteWise や Pythoku などのプロジェクトに参加し、Microsoft Learn Student Ambassador のメンティー。',
    team_axel_name:     'アクセル',
    team_axel_bio:      'テクニカル大学モンテレイ校の ITC 学生で、フロントエンド開発と Web プラットフォームに注力。Cuwi プラットフォームに貢献し、ハッカソンやデータソンに参加。Python、C++、MATLAB、HTML、CSS、JavaScript に熟練し、UX/UI デザイン、Blender モデリング、プロジェクト管理に強み。',
    team_marco_name:    'マルコ',
    team_marco_bio:     '創造的かつ技術的なスキルを持つ ITC 学生。Glup App プロジェクトに関わり、HackMTY の Oracle APEX チャレンジで優勝。Blender と SQL に精通。',
    team_david_name:    'デイビッド',
    team_david_bio:     'テクニカル大学モンテレイ校の ITC 学生。テクニカルスキルを備えた経験豊富な英語教師（Python、C++、MATLAB、Arduino、R）。技術と教育の背景を組み合わせ、細部に注意を払う。言語、プログラミング、インターフェースデザインに情熱を注ぐ。',
    team_fernando_name: 'フェルナンド',
    team_fernando_bio:  '自動化、チームワーク、クリティカルシンキングに長けた ITC 学生。Wi-Fi 制御を備えたスマートホームプロジェクトを開発し、全国ハッカソンのロジスティクスを調整。NGO と協力し技術支援の配布管理や市場調査を実施。',
    team_download_cv:   '履歴書をダウンロード',

    // --- registro.html ---
    register_title:     '登録',
    register_user:      'ユーザー',
    register_email:     'メール',
    register_password:  'パスワード',
    register_role:      '役割を選択：',
    register_role_user: 'ユーザー',
    register_role_admin:'管理者',
    register_submit:    '登録',
    register_have_account:'既にアカウントをお持ちですか？',

    // --- inicioSesion.html ---
    login_title:        'サインイン',
    login_username:     'ユーザー名',
    login_password:     'パスワード',
    login_button:       'サインイン',
    login_no_account:   'アカウントをお持ちでないですか？',
    login_sign_in:      "ログイン",


    // --- Tienda.html ---
    shop_title:          'ストア - LEXA Studios',
    shop_heading:        '商品',
    shop_item1_name:     'LEXA シャツ（黒）',
    shop_item1_price:    '¥3,500',
    shop_item2_name:     'LEXA シャツ（白）',
    shop_item2_price:    '¥3,500',
    shop_item3_name:     'Pixel Runner シャツ',
    shop_item3_price:    '¥3,500',
    shop_item4_name:     'Prof. Michi マグカップ',
    shop_item4_price:    '¥1,500',
    shop_item5_name:     'LEXA キャップ（黒）',
    shop_item5_price:    '¥1,500',
    shop_item6_name:     'LEXA キャップ（白）',
    shop_item6_price:    '¥1,500',
    shop_item7_name:     'ランナーズキャップ',
    shop_item7_price:    '¥1,500',
    shop_item8_name:     'Pixel Runner キーチェーン',
    shop_item8_price:    '¥1,500',
    shop_buy:            '購入',
    shop_modal_title:    '商品名',
    shop_modal_desc:     '商品説明',
    shop_size_label:     'サイズ：',
    shop_add_cart:       'カートに追加',
    shop_cart:           'カート',
    shop_pay:            '支払う',

    admin_new_admin:     '新しい管理者を作成',
    admin_create_btn:    '管理者を作成',
    'contact-messages':  'お問い合わせメッセージ',
    pw_min_length: "8文字以上であること",
    pw_uppercase:  "大文字を1つ以上含むこと",
    pw_lowercase:  "小文字を1つ以上含むこと",
    pw_digit:      "数字を1つ以上含むこと",
    pw_special:    "特殊文字を1つ以上含むこと",

    // --- juego.html ---
    game_title:         'ゲーム',
    game_page_title:    'Campus Bonanza',
    game_unavailable:   'ゲームは利用できません',
    scoreboard_title:   'スコアボード',
    scoreboard_col_name: '名前',
    scoreboard_col_score:'スコア',
    faq_heading:        'FAQ',
    faq_q1:             'どうやって遊ぶの？',
    faq_a1:             'Campus Bonanza はキャンパスの実際の事件を表すミニゲームに参加する RPG です。',
    faq_q2:             'どうやって勝つの？',
    faq_a2:             '速く効率的に事件を解決してポイントを獲得すると勝利します。',
    faq_q3:             'スコアシステムはどう機能しますか？',
    faq_a3:             'タスクを解決するたびにポイントが付与され、リーダーボードに表示されます。',
    faq_q4:             'スコアボードに登録するには？',
    faq_a4:             '名前、メールアドレス、パスワードでアカウントを作成すると、結果が自動的に保存されます。',
    faq_q5:             'パワーアップはどうやって機能しますか？',
    faq_a5:             '獲得したポイントを使って時間延長や速度アップなどのパワーアップを購入できます。'
  },

  ko: {
    // --- Header & Navbar ---
    nav_home:           '홈',
    nav_library:        '도서관',
    nav_merch:          '상품',
    nav_about:          '회사 소개',
    nav_contact:        '문의하기',
    nav_maintenance:    '관리',
    nav_language:       '🌎',
    nav_sign_in:        '로그인',
    nav_register:       '회원가입',
    user_label:         '사용자：',
    email_label:        '이메일：',
    avatar_change:      '아바타 변경',
    nav_sign_out:       '로그아웃',
    lang_spanish:       'Español',
    lang_english:       'English',
    lang_portuguese:    'Português',
    lang_chinese:       '中文',
    lang_japanese:      '日本語',
    lang_korean:        '한국어',
    lang_cyrillic:      'Кириллица',


    // --- index.html ---
    page_title_index:   '홈페이지',
    carousel_title_gta: 'GTA VI',
    carousel_desc_gta:  'Rockstar Games의 기대작 오픈 월드 게임, 가상의 플로리다 배경.',
    carousel_button:    '정보',
    carousel_title_doom:'Doom The Dark Ages',
    carousel_desc_doom: '중세를 배경으로 한 잔인한 FPS, DOOM (2016) 및 DOOM Eternal의 프리퀄.',
    carousel_title_mc:  'Minecraft',
    carousel_desc_mc:   '블록으로 구성된 세계를 탐험하고 건설하며 생존하는 최고의 샌드박스 게임.',
    carousel_prev:      '이전',
    carousel_next:      '다음',
    ods_label:          '지속가능발전목표:',
    ods_text:           '게임을 통해 학생들이 문제를 감지하고 보고하여 적극적인 참여와 대학 환경에 대한 관심을 촉진합니다.',
    game_label:         '게임:',
    game_text:          'Campus Bonanza는 교육용 RPG로, 학생들이 미니게임을 통해 캠퍼스 문제를 해결하여 참여를 유도합니다.',
    scope_label:        '범위:',
    scope_text:         '이 게임은 몬테레이 캠퍼스 학생들을 위해 설계되었으며, 미니게임, 파워업 상점, 점수 시스템 및 사고 보고 시스템을 포함합니다. WebGL을 통해 최신 브라우저에서 액세스할 수 있습니다.',

    // --- biblioteca.html ---
    lib_title:          '게임',
    lib_heading:        '도서관',
    lib_game1_title:    'Campus Bonanza',
    lib_game1_button:   '플레이',

    // --- Contacto.html ---
    contact_title:      '문의 - LEXA 스튜디오',
    contact_heading:    '문의하기',
    contact_form_title: '문의 양식',
    contact_name:       '이름',
    contact_email:      '이메일',
    contact_message:    '메시지',
    contact_send:       '보내기',
    contact_location:   '위치',
    contact_follow:     '팔로우하기',

    // --- Admin.html ---
    admin_title:        '관리 패널',
    admin_col_user:     '사용자',
    admin_col_email:    '이메일',
    admin_col_comment:  '댓글',
    admin_col_date:     '날짜',
    admin_col_status:   '상태',

    // --- Nosotros.html ---
    nosotros_title:     'LEXA 스튜디오',
    about_description:  'LEXA Studios는 몬테레이 공과대학 학생들로 구성된 팀으로, 사회적 영향을 미치는 상호작용 솔루션 개발에 주력합니다. 주요 프로젝트인 Campus Bonanza는 학생들이 캠퍼스 문제를 감지하고 해결하도록 하는 RPG 스타일의 비디오 게임으로 대학 환경을 개선하기 위해 고안되었습니다. 기술, 창의성 및 사회적 목적을 결합하여 웰빙, 협력 및 커뮤니티 인식을 촉진하는 혁신적인 경험을 만듭니다.',
    about_mission:      '미션',
    about_mission_text: '학생들이 대학 환경 개선에 참여하도록 장려하는 상호작용형 교육 도구를 개발하여 학습, 사회적 책임 및 협업을 촉진합니다.',
    about_values:       '가치',
    about_values_text:  '헌신, 창의성, 혁신, 협력, 사회적 책임 및 학생 커뮤니티와 그 환경에 대한 존중.',
    about_vision:       '비전',
    about_vision_text:  '기술과 사용자 중심 디자인을 통해 교육 커뮤니티에 긍정적인 변화를 불러일으키는 게임화 솔루션의 벤치마크가 되는 것.',
    tech_title:         '사용 기술',
    scope_heading:      '범위',
    scope_text:         'Campus Bonanza는 몬테레이 캠퍼스 학생을 대상으로 합니다. 시스템에는 사용자 등록, 역할 기반 로그인, 미니게임, 파워업 상점, 리더보드 및 사고 보고 시스템이 포함됩니다. WebGL을 통해 최신 브라우저에서 실행되며 AI 기반 개선을 통해 새로운 메커니즘 및 시나리오로 확장될 수 있는 잠재력을 갖추고 있습니다.',
    team_alexis_name:   '알렉시스',
    team_alexis_bio:    '몬테레이 공과대학 ITC 학생. API, 데이터 분석 및 관계형 데이터베이스 경험이 있는 백엔드 전문가. 임베디드 시스템 및 교육 혁신에 대한 열정이 있습니다. WasteWise 및 Pythoku와 같은 프로젝트에 참여했으며 Microsoft Learn Student Ambassador 멘티입니다.',
    team_axel_name:     '악셀',
    team_axel_bio:      '몬테레이 공과대학 ITC 학생으로 프론트엔드 개발 및 웹 플랫폼에 중점을 둡니다. Cuwi 플랫폼에 기여했으며 해커톤 및 데이터톤에 참여했습니다. Python, C++, MATLAB, HTML, CSS 및 JavaScript에 능숙합니다. UX/UI 설계 경험, Blender 모델링 및 프로젝트 관리 능력을 갖춘 창의적인 문제 해결사입니다.',
    team_marco_name:    '마르코',
    team_marco_bio:     '창의적이고 기술적인 기술을 모두 갖춘 ITC 학생. Glup App 프로젝트에 참여했으며 HackMTY의 Oracle APEX 챌린지에서 우승했습니다. Blender 및 SQL에 능숙합니다.',
    team_david_name:    '데이비드',
    team_david_bio:     '몬테레이 공과대학 ITC 학생. Python, C++, MATLAB, Arduino 및 R에 대한 기술 능력을 갖춘 경험 많은 영어 교사입니다. 세부 사항에 주의를 기울이며 기술 및 교육 배경을 결합합니다. 언어, 프로그래밍 및 인터페이스 디자인에 열정이 있습니다.',
    team_fernando_name: '페르난도',
    team_fernando_bio:  '자동화, 팀워크 및 비판적 사고 능력을 갖춘 ITC 학생. Wi-Fi 제어를 갖춘 스마트 홈 프로젝트를 개발했으며 전국 해커톤의 물류를 조율했습니다. NGO와 협력하여 기술 지원 제공 관리를 수행하고 시장 조사를 수행했습니다.',
    team_download_cv:   '이력서 다운로드',

    // --- registro.html ---
    register_title:     '회원가입',
    register_user:      '사용자',
    register_email:     '이메일',
    register_password:  '비밀번호',
    register_role:      '역할 선택:',
    register_role_user: '사용자',
    register_role_admin:'관리자',
    register_submit:    '가입하기',
    register_have_account:'이미 계정이 있습니까?',

    // --- inicioSesion.html ---
    login_title:        '로그인',
    login_username:     '사용자 이름',
    login_password:     '비밀번호',
    login_button:       '로그인',
    login_no_account:   '계정이 없습니까?',
    login_sign_in:      "로그인",

    // --- Tienda.html ---
    shop_title:          '상점 - LEXA Studios',
    shop_heading:        '상품',
    shop_item1_name:     'LEXA 셔츠(검정)',
    shop_item1_price:    '₩35,000',
    shop_item2_name:     'LEXA 셔츠(흰색)',
    shop_item2_price:    '₩35,000',
    shop_item3_name:     'Pixel Runner 셔츠',
    shop_item3_price:    '₩35,000',
    shop_item4_name:     'Prof. Michi 머그',
    shop_item4_price:    '₩15,000',
    shop_item5_name:     'LEXA 캡(검정)',
    shop_item5_price:    '₩15,000',
    shop_item6_name:     'LEXA 캡(흰색)',
    shop_item6_price:    '₩15,000',
    shop_item7_name:     '러너 캡',
    shop_item7_price:    '₩15,000',
    shop_item8_name:     'Pixel Runner 키체인',
    shop_item8_price:    '₩15,000',
    shop_buy:            '구매',
    shop_modal_title:    '제품 이름',
    shop_modal_desc:     '제품 설명',
    shop_size_label:     '사이즈:',
    shop_add_cart:       '장바구니에 추가',
    shop_cart:           '장바구니',
    shop_pay:            '결제',

    admin_new_admin:     '새 관리자 생성',
    admin_create_btn:    '관리자 생성',
    'contact-messages':  '문의 메시지',
    pw_min_length: "8자 이상이어야 합니다",
    pw_uppercase:  "대문자 하나 이상 포함",
    pw_lowercase:  "소문자 하나 이상 포함",
    pw_digit:      "숫자 하나 이상 포함",
    pw_special:    "특수 문자 하나 이상 포함",

    // --- juego.html ---
    game_title:         '게임',
    game_page_title:    'Campus Bonanza',
    game_unavailable:   '게임을 사용할 수 없습니다',
    scoreboard_title:   '점수판',
    scoreboard_col_name: '이름',
    scoreboard_col_score:'점수',
    faq_heading:        '자주 묻는 질문',
    faq_q1:             '어떻게 플레이하나요?',
    faq_a1:             'Campus Bonanza는 캠퍼스의 실제 사건을 나타내는 미니 게임에 참여하는 RPG 스타일 게임입니다.',
    faq_q2:             '어떻게 이기나요?',
    faq_a2:             '빠르고 효율적으로 사건을 해결하여 포인트를 획득하면 승리합니다.',
    faq_q3:             '점수 시스템은 어떻게 작동하나요?',
    faq_a3:             '작업을 해결할 때마다 포인트를 얻고 그 포인트는 점수판에 표시됩니다.',
    faq_q4:             '점수판에 어떻게 등록하나요?',
    faq_a4:             '이름, 이메일 및 비밀번호로 계정을 생성하면 결과가 자동으로 저장됩니다.',
    faq_q5:             '파워업은 어떻게 작동하나요?',
    faq_a5:             '획득한 포인트를 사용하여 추가 시간 또는 속도 증가와 같은 어드밴티지를 제공하는 파워업을 구매할 수 있습니다.'
  },

  ru: {
    // --- Header & Navbar ---
    nav_home:           'Главная',
    nav_library:        'Библиотека',
    nav_merch:          'Магазин',
    nav_about:          'О нас',
    nav_contact:        'Контакты',
    nav_maintenance:    'Обслуживание',
    nav_language:       '🌎',
    nav_sign_in:        'Войти',
    nav_register:       'Регистрация',
    user_label:         'Пользователь:',
    email_label:        'Эл. почта:',
    avatar_change:      'Сменить аватар',
    nav_sign_out:       'Выйти',
    lang_spanish:       'Español',
    lang_english:       'English',
    lang_portuguese:    'Português',
    lang_chinese:       '中文',
    lang_japanese:      '日本語',
    lang_korean:        '한국어',
    lang_cyrillic:      'Кириллица',


    // --- index.html ---
    page_title_index:   'Главная страница',
    carousel_title_gta: 'GTA VI',
    carousel_desc_gta:  'Долгожданная игра с открытым миром от Rockstar Games, действие в вымышленной Флориде.',
    carousel_button:    'Информация',
    carousel_title_doom:'Doom The Dark Ages',
    carousel_desc_doom: 'Жестокий шутер в средневековом мире, приквел DOOM (2016) и DOOM Eternal.',
    carousel_title_mc:  'Minecraft',
    carousel_desc_mc:   'Лучшая песочница, где можно исследовать, строить и выживать в процедурно сгенерированных мирах.',
    carousel_prev:      'Предыдущая',
    carousel_next:      'Следующая',
    ods_label:          'ЦУР:',
    ods_text:           'Через игру студенты выявляют и сообщают о проблемах, способствуя активному участию и заботе об университетской среде.',
    game_label:         'Игра:',
    game_text:          'Campus Bonanza — обучающее RPG, где студенты решают проблемы кампуса через мини-игры, повышая вовлеченность.',
    scope_label:        'Охват:',
    scope_text:         'Игра рассчитана на студентов кампуса Монтеррей, включает мини-игры, магазин улучшений, систему очков и отчетность об инцидентах. Работает в современных браузерах через WebGL.',

    // --- biblioteca.html ---
    lib_title:          'Игра',
    lib_heading:        'Библиотека',
    lib_game1_title:    'Campus Bonanza',
    lib_game1_button:   'Играть',

    // --- Contacto.html ---
    contact_title:      'Контакты - LEXA Studios',
    contact_heading:    'Свяжитесь с нами',
    contact_form_title: 'Форма обратной связи',
    contact_name:       'Имя',
    contact_email:      'Эл. почта',
    contact_message:    'Сообщение',
    contact_send:       'Отправить',
    contact_location:   'Местоположение',
    contact_follow:     'Подписывайтесь',

    // --- Admin.html ---
    admin_title:        'Панель управления',
    admin_col_user:     'Пользователь',
    admin_col_email:    'Эл. почта',
    admin_col_comment:  'Комментарий',
    admin_col_date:     'Дата',
    admin_col_status:   'Статус',

    // --- Nosotros.html ---
    nosotros_title:     'LEXA Studios',
    about_description:  'LEXA Studios — команда студентов Технологического института Монтеррея, занимающаяся разработкой интерактивных решений с социальным эффектом. Наш основной проект Campus Bonanza — это RPG-видеоигра, призванная улучшить университетскую среду, вовлекая студентов в выявление и решение проблем кампуса. Мы объединяем технологии, креативность и социальную цель, создавая инновационные решения, продвигающие благополучие, сотрудничество и осознанность сообщества.',
    about_mission:      'Миссия',
    about_mission_text: 'Разрабатывать интерактивные и образовательные инструменты, способствующие участию студентов в улучшении университетской среды, поощряя обучение, социальную ответственность и совместную работу.',
    about_values:       'Ценности',
    about_values_text:  'Обязательство, креативность, инновации, сотрудничество, социальная ответственность и уважение к студенческому сообществу и его окружению.',
    about_vision:       'Видение',
    about_vision_text:  'Стать эталоном в разработке игровых решений, вдохновляющих позитивные изменения в образовательных сообществах посредством технологий и ориентированного на пользователя дизайна.',
    tech_title:         'Используемые технологии',
    scope_heading:      'Охват',
    scope_text:         'Campus Bonanza предназначена для студентов кампуса Монтеррей. Система включает регистрацию пользователей, вход по ролям, мини-игры, магазин улучшений, лидерборд и систему отчетности об инцидентах. Работает в современных браузерах через WebGL и имеет потенциал для расширения новыми механиками, сценариями и улучшениями на основе ИИ.',
    team_alexis_name:   'Алексис',
    team_alexis_bio:    'Студент ITC в Технологическом институте Монтеррея. Специалист по бэкенду с опытом в API, анализе данных и реляционных базах данных. Увлечен встроенными системами и образовательными инновациями. Участвовал в проектах WasteWise и Pythoku, является младшим посланником Microsoft Learn Student Ambassador.',
    team_axel_name:     'Аксель',
    team_axel_bio:      'Студент ITC в Технологическом институте Монтеррея, сосредоточенный на фронтенд-разработке и веб-платформах. Внес вклад в платформу Cuwi и участвовал в хакатонах и дататонах. Умеет работать с Python, C++, MATLAB, HTML, CSS и JavaScript. Креативный UX/UI-дизайнер, эксперт по моделированию в Blender и талантливый менеджер проектов.',
    team_marco_name:    'Марко',
    team_marco_bio:     'Студент ITC с творческими и техническими навыками. Фронтенд-разработчик, цифровой художник и аниматор с опытом работы над Glup App и победитель Oracle APEX Challenge на HackMTY. Профессионал в Blender и SQL.',
    team_david_name:    'Дэвид',
    team_david_bio:     'Студент ITC в Технологическом институте Монтеррея. Опытный преподаватель английского языка с техническими навыками в Python, C++, MATLAB, Arduino и R. Сочетает технический и педагогический опыт с вниманием к деталям. Увлечен языками, программированием и дизайном интерфейсов.',
    team_fernando_name: 'Фернандо',
    team_fernando_bio:  'Студент ITC, обладающий навыками автоматизации, командной работы и критического мышления. Разработал проект умного дома с Wi-Fi управлением и координировал логистику на национальном хакатоне. Также сотрудничал с НКО, управляя доставкой технической помощи и проводя маркетинговые исследования.',
    team_download_cv:   'Скачать CV',

    // --- registro.html ---
    register_title:     'Регистрация',
    register_user:      'Пользователь',
    register_email:     'Эл. почта',
    register_password:  'Пароль',
    register_role:      'Выберите роль:',
    register_role_user: 'Пользователь',
    register_role_admin:'Администратор',
    register_submit:    'Зарегистрироваться',
    register_have_account:'Уже есть аккаунт?',

    // --- inicioSesion.html ---
    login_title:        'Войти',
    login_username:     'Имя пользователя',
    login_password:     'Пароль',
    login_button:       'Войти',
    login_no_account:   'Нет аккаунта?',
    login_sign_in:      "Вход в систему",

    // --- Tienda.html ---
    shop_title:          'Магазин - LEXA Studios',
    shop_heading:        'Товары',
    shop_item1_name:     'Футболка LEXA (Чёрная)',
    shop_item1_price:    '₽3500',
    shop_item2_name:     'Футболка LEXA (Белая)',
    shop_item2_price:    '₽3500',
    shop_item3_name:     'Футболка Pixel Runner',
    shop_item3_price:    '₽3500',
    shop_item4_name:     'Кружка Prof. Michi',
    shop_item4_price:    '₽1500',
    shop_item5_name:     'Бейсболка LEXA (Чёрная)',
    shop_item5_price:    '₽1500',
    shop_item6_name:     'Бейсболка LEXA (Белая)',
    shop_item6_price:    '₽1500',
    shop_item7_name:     'Бейсболка Runner',
    shop_item7_price:    '₽1500',
    shop_item8_name:     'Брелок Pixel Runner',
    shop_item8_price:    '₽1500',
    shop_buy:            'Купить',
    shop_modal_title:    'Название товара',
    shop_modal_desc:     'Описание товара',
    shop_size_label:     'Размер:',
    shop_add_cart:       'Добавить в корзину',
    shop_cart:           'Корзина',
    shop_pay:            'Оплатить',

    admin_new_admin:     'Создать нового администратора',
    admin_create_btn:    'Создать админа',
    'contact-messages':  'Сообщения контакта',
    pw_min_length: "Не менее 8 символов",
    pw_uppercase:  "Минимум одна заглавная буква",
    pw_lowercase:  "Минимум одна строчная буква",
    pw_digit:      "Минимум одна цифра",
    pw_special:    "Минимум один специальный символ",
    
    // --- juego.html ---
    game_title:         'Игра',
    game_page_title:    'Campus Bonanza',
    game_unavailable:   'Игра недоступна',
    scoreboard_title:   'Таблица рекордов',
    scoreboard_col_name: 'Имя',
    scoreboard_col_score:'Очки',
    faq_heading:        'Часто задаваемые вопросы',
    faq_q1:             'Как играть?',
    faq_a1:             'Campus Bonanza — это RPG, где вы участвуете в мини-играх, являющихся отражением реальных инцидентов на кампусе.',
    faq_q2:             'Как победить?',
    faq_a2:             'Вы побеждаете, набирая очки за быстрое и эффективное решение инцидентов.',
    faq_q3:             'Как работает система очков?',
    faq_a3:             'Каждый раз, когда вы решаете задачу, вы набираете очки, которые отображаются в таблице рекордов.',
    faq_q4:             'Как зарегистрироваться в таблице рекордов?',
    faq_a4:             'Создайте аккаунт с именем, почтой и паролем, и ваши результаты будут сохранены автоматически.',
    faq_q5:             'Как работают усилители (power-ups)?',
    faq_a5:             'Используйте заработанные очки, чтобы покупать усилители, которые дают преимущества, такие как дополнительное время или увеличение скорости.'
  }
};

// Idioma actualmente seleccionado (se inicializa luego de leer localStorage)
let currentLang = localStorage.getItem('language') || 'es';

// ==== Aplica traducciones a todos los elementos con data-i18n dentro de un root dado ====
function applyTranslations(lang, root = document) {
  root.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      el.innerText = translations[lang][key];
    }
  });
}

// ==== Guarda el idioma en localStorage y re-aplica traducción en todo el documento ====
function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('language', lang);
  applyTranslations(lang);
}

// ==== Cuando el DOM esté listo ====
document.addEventListener('DOMContentLoaded', () => {
  // 1) Aplicar traducción inicial al contenido ya existente
  applyTranslations(currentLang);

  // 2) Montar el MutationObserver para detectar nuevos nodos con data-i18n
  const observer = new MutationObserver(mutations => {
    mutations.forEach(mutation => {
      mutation.addedNodes.forEach(node => {
        if (node.nodeType !== Node.ELEMENT_NODE) return;
        // Traducir el nodo agregado (si mismo y sus hijos que tengan data-i18n)
        applyTranslations(currentLang, node);
      });
    });
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true
  });

  // 3) Asignar eventos a los botones de cambio de idioma
  function attachLanguageButtons() {
    const buttons = document.querySelectorAll('.language-option');
    if (buttons.length === 0) {
      // Si aún no existe el dropdown (header no inyectado), reintentar en 50ms
      setTimeout(attachLanguageButtons, 50);
      return;
    }
    buttons.forEach(btn => {
      btn.addEventListener('click', () => {
        const lang = btn.getAttribute('data-lang');
        setLanguage(lang);
      });
    });
  }

  attachLanguageButtons();
});